Updating with folder tests_homework_11.py
annamariaqa/homework_hillel_1609 pull request #10
Opened 2024-10-27 09:44 UTC by annamariaqa

2024-10-27 09:46 UTC, annamariaqa commented on tests_homework_11.py/test_login.py
> +with open("login_system.log", "r", encoding="utf-8") as file:
@MrCrow79 я хотіла так перевірити що в файлі з логами у мене додаються username та status і щоб виводило які саме додаються, схоже це не спрацювало(

2024-10-27 20:25 UTC, MrCrow79 requested changes

2024-10-27 20:25 UTC, MrCrow79 commented on tests_homework_11.py/test_login.py
> +with open("login_system.log", "r", encoding="utf-8") as file:
Я не дуже розумію яким чином ти хотіла перевірити)
В сенсі ти створила функцію check_logger_file але ти її ж не викликала - тобто вона не спрацювала

Якщо я зрозумів ідею, то яб зробив зробити так:

```
if __name__ == '__main__':  #  Захист від спрацьовування при імпорті


    # спочатку створити функцію
    def check_logger_file(username, status, log_text):
        if username in log_text and status in log_text:
            return True  # логічно повертати True або False в функції якщо щось перевіряє
        return False

        # у тебе було щось типу status == str in text.
        # тобто ти писала
        # status == str - значення змінної status це str(не тип змінної, а сама змінна), це буде False
        # if False in text - якщо ьулева змінна в text

    user = 'Alex'
    status = 'unknown'
    log_event(user, status)

    # потім вичитати дані з файлу і помістити це в змінну text
    with open("login_system.log", "r") as file:  # encoding="utf-8" - в python 3.x це не треба, воно і так буде utf-8 читати, якщо не скажеш інше
        text = file.read()

    print(f'Log is correct: {check_logger_file(user, status, text)} ')
```

2024-10-27 20:25 UTC, MrCrow79 commented on tests_homework_11.py/test_for_login_positive.py
> +        assert True
це тест завжди буде зеленим

давай його розберемо построчно:
`actual_result = log_event(username='Anna', status='success')`

У тебе функція log_event не повертає нічого. ТОбто у тебе actual_result завжди буде None

`expected_result = str `
Ти в змінну expected_result записуєш тип str. Для чого я не дуже розумію

```
if actual_result == expected_result:
    assert True
```
А тут якщо у тебе expected == actual, то ти просто перевіриш що True це True і нічого ен зробиш
Я якщо expected != actual, то просто нічого не зробиш

У тебе тести нічого не роблять, це хибно-позитивні тести. Тобто тети які просто будуть завжди зеленими

Подивись на функцію  check_logger_file
Там, фактично, прописана перевірка наявності тексту в файлі.
Давай почнемо з того, що ти використаєш ту перевірку.

Якщо ти це зробиш - я зарахую дз
Якщо ти хочеш піти далі - то перевіряй не весь текст, а тільки останню строку

2024-11-04 19:20 UTC, MrCrow79 commented on tests_homework_11.py/test_login.py
> +        content = file_.read()
`last_row =  file.readlines()[-1]`

2024-11-04 19:21 UTC, MrCrow79 commented on tests_homework_11.py/test_login.py
> +        assert expected_row in last_row
```
with open('login_system.log', 'r') as file_:
        content = file_.read()
        ...
expected_row = log_message
assert expected_row in last_row
```

2024-11-04 19:57 UTC, MrCrow79 approved these changes

2024-11-09 19:55 UTC, merged